### ISSUE TITLE
It can't be used

### ISSUE THREAD

**Issue by Waterman178** [SinaKarvandi/HyperDbg#1]
Many functions are not available.Failed to load the kernel module locally.It prompts that the entrance cannot be found.There is no tutorial

**Comment by SinaKarvandi** [comment]
Hello,
Would you please post the errors? Did you install WDK (Windows Driver Kit) on your Visual Studio?
Did you change the project configuration to build & compile for x64?

**Comment by SinaKarvandi** [comment]
Sorry, I thought you send a comment for Hypervisor From Scratch !!! It's HyperDbg.

As I mentioned in both the project website and GitHub, this project is not yet ready/finished. It will be released probably in October. If you want to use a hypervisor, you can use Hypervisor From Scratch.
